"""changed name of book_price -> prive

Revision ID: 381f15310027
Revises: 776e18270df0
Create Date: 2025-04-21 15:05:16.906593

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381f15310027'
down_revision: Union[str, None] = '776e18270df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('order_item', 'book_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('book_price', sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.drop_column('order_item', 'price')
    # ### end Alembic commands ###
