# In alembic/versions/776e18270df0_discount_end_date_should_be_nullable.py

from alembic import op
import sqlalchemy as sa
# Make sure you import any necessary types like sa.DATE

# revision identifiers, used by Alembic.
revision = '776e18270df0'
down_revision = 'ecadf813f5d9' # Previous revision ID
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.alter_column('discount_end_date',
               existing_type=sa.DATE(), # Make sure existing_type is correct!
               nullable=True)           # Change to nullable

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.alter_column('discount_end_date',
               existing_type=sa.DATE(), # Make sure existing_type is correct!
               nullable=False)          # Change back to non-nullable

    # ### end Alembic commands ###