"""rename table migration

Revision ID: db3bafd9e592
Revises: 08ff83bda4d9
Create Date: 2025-04-13 14:24:50.142523

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3bafd9e592'
down_revision: Union[str, None] = '08ff83bda4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_book_id'), 'order_item', ['book_id'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.drop_index('ix_orderitem_book_id', table_name='orderitem')
    op.drop_index('ix_orderitem_order_id', table_name='orderitem')
    op.drop_table('orderitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orderitem_order_id', 'orderitem', ['order_id'], unique=False)
    op.create_index('ix_orderitem_book_id', 'orderitem', ['book_id'], unique=False)
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_book_id'), table_name='order_item')
    op.drop_table('order_item')
    # ### end Alembic commands ###
